"""Constructor de carteras UBS con DD discreto y restricciones.

Este modulo es intencionadamente puro: ni Tkinter ni SQLite. Recibe sets
aceptados por robustez, fusiona sus informes 2020-2024 y 2025-2026 en una
curva 2020-2026 y asigna lotes en unidades enteras de 0.01. Cada incremento
posible se evalua contra la curva completa antes de aceptarse.

Era un solo fichero de 6.800 lineas. Ahora el orden de los imports de abajo
es el orden de dependencia: cada modulo solo usa los anteriores.
"""

from __future__ import annotations

from .symbols import (
    PORTFOLIO_GROUP_BY_SYMBOL, PORTFOLIO_SYMBOL_ALIASES, PORTFOLIO_UNIVERSE_FILES, _ascii_text,
    _looks_like_forex_pair, _normalize_symbol, _normalized_universe_group, _portfolio_universe_display_maps_for_files,
    _portfolio_universe_display_symbol, _portfolio_universe_files_key, _portfolio_universe_group_by_symbol, _portfolio_universe_group_maps,
    _portfolio_universe_group_maps_for_files, _portfolio_universe_symbol_base, portfolio_display_symbol, portfolio_group_key,
    portfolio_symbol_key,
)
from .models import (
    BOOTSTRAP_METHOD, BootstrapDrawdownAnalysis, CancellationCheck, ClosedTrade,
    CorrelationPair, DEFAULT_BOOTSTRAP_SEED, DEFAULT_BOOTSTRAP_SIMULATIONS, DEFAULT_GROUP_LIMITS,
    MIN_RECENT_EQUITY_RECOVERY, OptimizationDecision, PeriodReport, PortfolioAvailability,
    PortfolioCalculationCancelled, PortfolioEvaluation, PortfolioGroupLimits, PortfolioResult,
    PortfolioType, ProgressCallback, RobustStrategySet, StrategyAllocation,
    UnusedSetInfo, _CANCELLATION_STATE, _raise_if_portfolio_cancelled, group_limits_for_portfolio_type,
    set_portfolio_cancellation_check,
)
from .rows import (
    _coerce_month_end, _first_existing_report_path, _latest_month_from_monthly, _logical_stem,
    _lot_size_step, _month_window, _norm_path, _parse_report_date,
    _row_int, _row_value, _step_for_max_units, _to_float,
    execution_units_from_step,
)
from .curves import (
    _curve_points_from_closed_trades, _linear_percentile, _merge_curve_points, bootstrap_valley_drawdown,
    build_correlation_pairs, calc_point_dd, calc_valley_dd, curve_increment_correlation,
    daily_pnl_series, merge_accumulated_curves, merge_incremental_curves, pearson_correlation,
    portfolio_daily_closed_floating_dd, portfolio_floating_overlap_audit, strategy_correlation_pair, strategy_daily_closed_floating_dd,
    to_accumulated_curve,
)
from .monthly_validation import (
    _StrictMonthlyContext, _curve_metrics, _dd_passed, _dominant_month,
    _empty_validation, _month_validation, _monthly_validations, _portfolio_increments,
    _validation_window, _year_validation, validate_strict_monthly_portfolio,
)
from .reports import (
    _chronological_closed_trade_history, _first_metric, _full_history_report_covers_segmented_history, _metric_amount,
    _period_years, _report_period_bounds, _validate_curve_against_net, _validate_period_order,
    build_equity_curve_from_closed_trades, build_robust_strategy_set, calc_combined_profit_factor, extract_period_info,
    maximal_drawdowns_from_report, parse_mt5_html_report, period_report_from_strategy_report, slice_strategy_set_to_month,
    slice_strategy_sets_to_month,
)
from .selection import (
    _CandidateReports, _LoadStats, _RobustSetLoader, _limit_candidates_with_group_reserve,
    filter_eligible_sets, filter_rows_by_recent_positive_months, filter_rows_grid_off, load_robust_sets_from_rows,
    recent_positive_month_count, score_set_for_portfolio, select_top_k_per_symbol, set_file_has_enabled_grid,
    summarize_robust_rows,
)
from .evaluation import (
    _evaluate_portfolio_on_time_axis, _evaluation_violates_dd_limits, _evaluation_violation_ratio, evaluate_portfolio,
    portfolio_group_summary,
)
from .margin import (
    ACCOUNT_LEVERAGE_CHOICES, AXI_FALLBACK_GROUP_LEVERAGE, DEFAULT_ACCOUNT_LEVERAGE, MARGIN_PROFILES,
    MARGIN_PROFILE_LABELS, MarginModel, _load_json_dict, allocation_margin_required,
    allocation_notional, allocations_respect_margin_limit, load_max_product_leverage, load_symbol_notional,
    load_symbol_notional_from_specs, load_symbol_specs, load_unmeasured_symbols, margin_contract_size_for_profile,
    margin_leverage_for_profile, margin_model_for_profile, margin_profile_label, normalize_margin_profile,
    portfolio_margin_summary, resolve_margin_model, roboforex_contract_size, roboforex_margin_leverage,
    strategy_reference_price, ttp_leverage_for,
)
from .limits import (
    CandidateFunnel, SearchLimits, SearchPlan, _OPTIMIZER_BAGS,
    optimizer_overrides,
)
from .constraints import (
    _allocations_respect_constraints, _candidate_group_count, _portfolio_active_count, _portfolio_corr_allowed,
    _target_group_units_pct_allowed, can_add_unit, score_increment, violates_correlation_limits,
)
from .execution import (
    _build_unused_sets, _execution_plan_allocations, _repair_executable_allocations, apply_portfolio_lot_text,
    set_current_value,
)
from .greedy import (
    _DeepScan, _IncrementRules, _StepScan, _active_unit_allocations,
    _added_unit_decision, _best_deep_move, _best_swap, _caps_allow,
    _consider_increment, _deep_add_move, _deep_decision, _deep_gain,
    _deep_refine_allocations, _deep_swap_move, _greedy_start, _greedy_stop_reason,
    _keep_best_candidate, _note_dd_block, _perturb_decision, _perturbation_move,
    _perturbed_trial, _portfolio_corr_allows, _portfolio_corr_rejects, _repair_reduction,
    _run_greedy_steps, _scan_step, _slot_allows_increment, _swap_candidate,
    _swap_decision, _swap_respects_caps, _swap_respects_correlation, build_portfolio_greedy,
    improve_with_local_search, improve_with_multi_start_search,
)
from .optimize_search import (
    _CandidatePool, _DeepRefinement, _PassContext, _SearchPass,
    _apply_deep_refinement, _build_candidate_pool, _deep_refinement_pool, _feasible_group_units_pct,
    _greedy_then_local_search, _multi_start_pass, _relaxed_group_cap_pass, _repair_to_executable_lots,
)
from .optimize_results import (
    _allocation_row, _axi_margin_rule_text, _build_portfolio_result, _daily_dd_warning,
    _dd_composition_warnings, _deep_refinement_warning, _default_margin_rule_text, _group_floor_warning,
    _group_limit_overages, _margin_and_daily_summaries, _margin_warning, _recent_recovery_warning,
    _result_allocation_rows, _search_phase_warnings, _ttp_margin_rule_text, _usage_warnings,
)
from .optimize_flow import (
    _Measured, _OptimizationPlan, _SearchOutcome, _apply_deep_pass,
    _apply_executable_rounding, _apply_greedy_pass, _apply_multi_start, _finish_portfolio,
    _measure_portfolio, _optimizer_warnings, _prepare_optimization, _run_search_phases,
)
from .optimize import (
    optimize_portfolio,
)
from .strict_monthly_candidates import (
    _MonthlyReduction, _best_monthly_reduction, _distinct_monthly_variants, _limit_sorted_candidates_with_symbol_reserve,
    _monthly_orderings, _monthly_reduction_decision, _repair_allocations_to_strict_monthly, _strict_monthly_candidate_score,
    _strict_monthly_candidate_validation, _strict_monthly_candidate_variants, _strict_monthly_violation_score, _strict_validation_for_allocations,
)
from .strict_monthly_refinement import (
    _best_monthly_deep_move, _best_monthly_refill, _monthly_add_candidate, _monthly_deep_decision,
    _monthly_evaluate, _monthly_gain, _monthly_refill_decision, _monthly_swap_candidate,
    _ordered_monthly_targets, _strict_monthly_deep_refine_allocations, _strict_monthly_safe_refill_allocations,
)
from .strict_monthly import (
    _MonthlyOptimizerArgs, _active_units_of, _drop_preserved_warning, _monthly_base_evaluation,
    _monthly_candidate_pool, _monthly_deep_refine, _monthly_safe_refill, _rebuild_after_strict_repair,
    _reoptimize_locked_monthly, _select_strict_monthly_base, _strict_monthly_limits, _strict_monthly_search,
    _strict_monthly_variant_result, optimize_strict_monthly_portfolio,
)

__all__ = [
    "ACCOUNT_LEVERAGE_CHOICES",
    "AXI_FALLBACK_GROUP_LEVERAGE",
    "BOOTSTRAP_METHOD",
    "BootstrapDrawdownAnalysis",
    "CancellationCheck",
    "CandidateFunnel",
    "ClosedTrade",
    "CorrelationPair",
    "DEFAULT_ACCOUNT_LEVERAGE",
    "DEFAULT_BOOTSTRAP_SEED",
    "DEFAULT_BOOTSTRAP_SIMULATIONS",
    "DEFAULT_GROUP_LIMITS",
    "MARGIN_PROFILES",
    "MARGIN_PROFILE_LABELS",
    "MIN_RECENT_EQUITY_RECOVERY",
    "MarginModel",
    "OptimizationDecision",
    "PORTFOLIO_GROUP_BY_SYMBOL",
    "PORTFOLIO_SYMBOL_ALIASES",
    "PORTFOLIO_UNIVERSE_FILES",
    "PeriodReport",
    "PortfolioAvailability",
    "PortfolioCalculationCancelled",
    "PortfolioEvaluation",
    "PortfolioGroupLimits",
    "PortfolioResult",
    "PortfolioType",
    "ProgressCallback",
    "RobustStrategySet",
    "SearchLimits",
    "SearchPlan",
    "StrategyAllocation",
    "UnusedSetInfo",
    "_CANCELLATION_STATE",
    "_CandidatePool",
    "_CandidateReports",
    "_DeepRefinement",
    "_DeepScan",
    "_IncrementRules",
    "_LoadStats",
    "_Measured",
    "_MonthlyOptimizerArgs",
    "_MonthlyReduction",
    "_OPTIMIZER_BAGS",
    "_OptimizationPlan",
    "_PassContext",
    "_RobustSetLoader",
    "_SearchOutcome",
    "_SearchPass",
    "_StepScan",
    "_StrictMonthlyContext",
    "_active_unit_allocations",
    "_active_units_of",
    "_added_unit_decision",
    "_allocation_row",
    "_allocations_respect_constraints",
    "_apply_deep_pass",
    "_apply_deep_refinement",
    "_apply_executable_rounding",
    "_apply_greedy_pass",
    "_apply_multi_start",
    "_ascii_text",
    "_axi_margin_rule_text",
    "_best_deep_move",
    "_best_monthly_deep_move",
    "_best_monthly_reduction",
    "_best_monthly_refill",
    "_best_swap",
    "_build_candidate_pool",
    "_build_portfolio_result",
    "_build_unused_sets",
    "_candidate_group_count",
    "_caps_allow",
    "_chronological_closed_trade_history",
    "_coerce_month_end",
    "_consider_increment",
    "_curve_metrics",
    "_curve_points_from_closed_trades",
    "_daily_dd_warning",
    "_dd_composition_warnings",
    "_dd_passed",
    "_deep_add_move",
    "_deep_decision",
    "_deep_gain",
    "_deep_refine_allocations",
    "_deep_refinement_pool",
    "_deep_refinement_warning",
    "_deep_swap_move",
    "_default_margin_rule_text",
    "_distinct_monthly_variants",
    "_dominant_month",
    "_drop_preserved_warning",
    "_empty_validation",
    "_evaluate_portfolio_on_time_axis",
    "_evaluation_violates_dd_limits",
    "_evaluation_violation_ratio",
    "_execution_plan_allocations",
    "_feasible_group_units_pct",
    "_finish_portfolio",
    "_first_existing_report_path",
    "_first_metric",
    "_full_history_report_covers_segmented_history",
    "_greedy_start",
    "_greedy_stop_reason",
    "_greedy_then_local_search",
    "_group_floor_warning",
    "_group_limit_overages",
    "_keep_best_candidate",
    "_latest_month_from_monthly",
    "_limit_candidates_with_group_reserve",
    "_limit_sorted_candidates_with_symbol_reserve",
    "_linear_percentile",
    "_load_json_dict",
    "_logical_stem",
    "_looks_like_forex_pair",
    "_lot_size_step",
    "_margin_and_daily_summaries",
    "_margin_warning",
    "_measure_portfolio",
    "_merge_curve_points",
    "_metric_amount",
    "_month_validation",
    "_month_window",
    "_monthly_add_candidate",
    "_monthly_base_evaluation",
    "_monthly_candidate_pool",
    "_monthly_deep_decision",
    "_monthly_deep_refine",
    "_monthly_evaluate",
    "_monthly_gain",
    "_monthly_orderings",
    "_monthly_reduction_decision",
    "_monthly_refill_decision",
    "_monthly_safe_refill",
    "_monthly_swap_candidate",
    "_monthly_validations",
    "_multi_start_pass",
    "_norm_path",
    "_normalize_symbol",
    "_normalized_universe_group",
    "_note_dd_block",
    "_optimizer_warnings",
    "_ordered_monthly_targets",
    "_parse_report_date",
    "_period_years",
    "_perturb_decision",
    "_perturbation_move",
    "_perturbed_trial",
    "_portfolio_active_count",
    "_portfolio_corr_allowed",
    "_portfolio_corr_allows",
    "_portfolio_corr_rejects",
    "_portfolio_increments",
    "_portfolio_universe_display_maps_for_files",
    "_portfolio_universe_display_symbol",
    "_portfolio_universe_files_key",
    "_portfolio_universe_group_by_symbol",
    "_portfolio_universe_group_maps",
    "_portfolio_universe_group_maps_for_files",
    "_portfolio_universe_symbol_base",
    "_prepare_optimization",
    "_raise_if_portfolio_cancelled",
    "_rebuild_after_strict_repair",
    "_recent_recovery_warning",
    "_relaxed_group_cap_pass",
    "_reoptimize_locked_monthly",
    "_repair_allocations_to_strict_monthly",
    "_repair_executable_allocations",
    "_repair_reduction",
    "_repair_to_executable_lots",
    "_report_period_bounds",
    "_result_allocation_rows",
    "_row_int",
    "_row_value",
    "_run_greedy_steps",
    "_run_search_phases",
    "_scan_step",
    "_search_phase_warnings",
    "_select_strict_monthly_base",
    "_slot_allows_increment",
    "_step_for_max_units",
    "_strict_monthly_candidate_score",
    "_strict_monthly_candidate_validation",
    "_strict_monthly_candidate_variants",
    "_strict_monthly_deep_refine_allocations",
    "_strict_monthly_limits",
    "_strict_monthly_safe_refill_allocations",
    "_strict_monthly_search",
    "_strict_monthly_variant_result",
    "_strict_monthly_violation_score",
    "_strict_validation_for_allocations",
    "_swap_candidate",
    "_swap_decision",
    "_swap_respects_caps",
    "_swap_respects_correlation",
    "_target_group_units_pct_allowed",
    "_to_float",
    "_ttp_margin_rule_text",
    "_usage_warnings",
    "_validate_curve_against_net",
    "_validate_period_order",
    "_validation_window",
    "_year_validation",
    "allocation_margin_required",
    "allocation_notional",
    "allocations_respect_margin_limit",
    "apply_portfolio_lot_text",
    "bootstrap_valley_drawdown",
    "build_correlation_pairs",
    "build_equity_curve_from_closed_trades",
    "build_portfolio_greedy",
    "build_robust_strategy_set",
    "calc_combined_profit_factor",
    "calc_point_dd",
    "calc_valley_dd",
    "can_add_unit",
    "curve_increment_correlation",
    "daily_pnl_series",
    "evaluate_portfolio",
    "execution_units_from_step",
    "extract_period_info",
    "filter_eligible_sets",
    "filter_rows_by_recent_positive_months",
    "filter_rows_grid_off",
    "group_limits_for_portfolio_type",
    "improve_with_local_search",
    "improve_with_multi_start_search",
    "load_max_product_leverage",
    "load_robust_sets_from_rows",
    "load_symbol_notional",
    "load_symbol_notional_from_specs",
    "load_symbol_specs",
    "load_unmeasured_symbols",
    "margin_contract_size_for_profile",
    "margin_leverage_for_profile",
    "margin_model_for_profile",
    "margin_profile_label",
    "maximal_drawdowns_from_report",
    "merge_accumulated_curves",
    "merge_incremental_curves",
    "normalize_margin_profile",
    "optimize_portfolio",
    "optimize_strict_monthly_portfolio",
    "optimizer_overrides",
    "parse_mt5_html_report",
    "pearson_correlation",
    "period_report_from_strategy_report",
    "portfolio_daily_closed_floating_dd",
    "portfolio_display_symbol",
    "portfolio_floating_overlap_audit",
    "portfolio_group_key",
    "portfolio_group_summary",
    "portfolio_margin_summary",
    "portfolio_symbol_key",
    "recent_positive_month_count",
    "resolve_margin_model",
    "roboforex_contract_size",
    "roboforex_margin_leverage",
    "score_increment",
    "score_set_for_portfolio",
    "select_top_k_per_symbol",
    "set_current_value",
    "set_file_has_enabled_grid",
    "set_portfolio_cancellation_check",
    "slice_strategy_set_to_month",
    "slice_strategy_sets_to_month",
    "strategy_correlation_pair",
    "strategy_daily_closed_floating_dd",
    "strategy_reference_price",
    "summarize_robust_rows",
    "to_accumulated_curve",
    "ttp_leverage_for",
    "validate_strict_monthly_portfolio",
    "violates_correlation_limits",
]
