; RoboForex ECN universe imported from:
; C:\Users\Adrian\Adrian\TRADING\InstrumentosECN_robo.docx
; Updated on 2026-06-02.

[Forex]
symbols=AUDCAD,AUDCHF,AUDJPY,AUDNZD,AUDUSD,CADCHF,CADJPY,CHFJPY,GBPAUD,GBPCAD,GBPCHF,GBPJPY,GBPNZD,GBPUSD,EURAUD,EURCAD,EURCHF,EURGBP,EURJPY,EURNZD,EURUSD,NZDCAD,NZDCHF,NZDJPY,NZDUSD,USDCAD,USDCHF,USDJPY

[Metals]
symbols=XAGUSD,XAUUSD,XAUEUR

[IndicesEnergies]
symbols=.DE40Cash,.JP225Cash,.US500Cash,.USTECHCash,.US30Cash,BRENT,WTI

[Crypto]
symbols=BTCUSD,ETHUSD

[Stocks]
symbols=GOOGL,MSFT,IBM,VZ,INTC,LLY,HPE,PFE,JNJ,EA,BA,ORCL,NVDA,CAT,CSCO,MMM,ADBE,GE,TSLA,NKE,CMCSA,GM,DIS,PM,PG,PEP,FOXA,KO,AAPL,AMZN,UPS,NFLX,BRK.B,MCD,PRU,SBUX,PYPL,GS,WMT,V,DAL,WFC,C,XOM,CVX,NEM,JPM,BAC,EBAY,META

[CommonAliases]
US30=.US30Cash
US500=.US500Cash
USTEC=.USTECHCash
US100=.USTECHCash
NAS100=.USTECHCash
DAX=.DE40Cash
DE40=.DE40Cash
GER40=.DE40Cash
XTIUSD=WTI
USOIL=WTI
CRUDEOIL=WTI
